-- ── Savored: add the fourth article category ──────────────────
--
-- HOW TO RUN THIS
--
-- This project has no DATABASE_URL and no psql/Supabase CLI installed, so
-- there is no command-line path. Paste this file into the Supabase SQL editor:
--
--   https://supabase.com/dashboard/project/jojhqdfsuhwqugtgkppt/sql/new
--
-- WHY IT IS NEEDED
--
-- schema.sql uses `create table if not exists`, so editing the inline check
-- constraint there does nothing to an existing database. Until this runs, any
-- article saved with category 'food' is rejected by the live table.
--
--   review    → Heard
--   news      → Around
--   spotlight → Seen
--   food      → Savored   (new — matches the `food` key already used by the
--                          events table, the calendar, and the savored→food
--                          normalisation in app/api/admin/events/route.js)
--
-- Safe to run more than once.

-- Step 1. Drop every check constraint on articles.category, whatever it is
-- named. The constraint is declared inline in schema.sql, so its name was
-- auto-generated by Postgres — on most databases that is
-- `articles_category_check`, but dropping only that name would silently leave
-- a differently-named constraint in place, still rejecting 'food', while the
-- new one was added beside it. This finds them by definition instead.

do $$
declare
  c record;
begin
  for c in
    select con.conname
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where rel.relname  = 'articles'
      and nsp.nspname  = 'public'
      and con.contype  = 'c'
      and pg_get_constraintdef(con.oid) ilike '%category%'
  loop
    raise notice 'dropping constraint %', c.conname;
    execute format('alter table public.articles drop constraint %I', c.conname);
  end loop;
end $$;

-- Step 2. Add it back with 'food' included.

alter table public.articles
  add constraint articles_category_check
  check (category in ('review', 'news', 'spotlight', 'food'));

-- Step 3. Verify. Should return one row whose definition lists all four.

select con.conname, pg_get_constraintdef(con.oid) as definition
from pg_constraint con
join pg_class rel on rel.oid = con.conrelid
join pg_namespace nsp on nsp.oid = rel.relnamespace
where rel.relname = 'articles'
  and nsp.nspname = 'public'
  and con.contype = 'c'
  and pg_get_constraintdef(con.oid) ilike '%category%';
