export const CATEGORIES = ['review', 'news', 'spotlight']
export const CATEGORY_LABELS = { review: 'Heard', news: 'Around', spotlight: 'Seen' }
export const CATEGORY_COLOR = { review: '#E73B2F', news: '#C95C2B', spotlight: '#2D4DFF' }

export const NOISE_SVG = `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.08'/%3E%3C/svg%3E")`

export const DARK_ZONE = {
  background: '#111111',
  position: 'relative',
  overflow: 'hidden',
}

export const LIGHT_ZONE = {
  background: '#F5F1E8',
  position: 'relative',
}

export const NOISE_OVERLAY = {
  position: 'absolute',
  top: 0, left: 0, right: 0, bottom: 0,
  backgroundImage: NOISE_SVG,
  backgroundRepeat: 'repeat',
  backgroundSize: '256px 256px',
  pointerEvents: 'none',
  zIndex: 0,
  opacity: 0.035,
}

export const CONTENT = {
  position: 'relative',
  zIndex: 1,
  maxWidth: 960,
  margin: '0 auto',
  padding: '0 24px',
}

export const CONTENT_LIGHT = {
  maxWidth: 960,
  margin: '0 auto',
  padding: '0 24px 48px',
}

export const STYLES = {
  header: {
    padding: '40px 0 28px',
  },
  masthead: {
    fontFamily: "'Outfit', sans-serif",
    fontWeight: 900,
    fontSize: 'clamp(48px, 9.35vw, 82px)',
    letterSpacing: '0.012em',
    lineHeight: 0.78,
    textTransform: 'uppercase',
    margin: 0,
    padding: 0,
    display: 'block',
    textAlign: 'left',
  },
  tagline: {
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: '3px',
    color: '#8A8A8A',
    marginTop: 14,
  },
  nav: {
    display: 'flex',
    gap: 0,
    borderTop: '1px solid #2A2A2A',
    borderBottom: '1px solid #2A2A2A',
  },
  navItem: (active) => ({
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: '2.5px',
    padding: '14px 20px',
    cursor: 'pointer',
    background: active ? '#F5F1E8' : 'transparent',
    color: active ? '#111111' : '#8A8A8A',
    border: 'none',
    fontWeight: 600,
    transition: 'all 0.15s',
  }),
  card: {
    borderBottom: '1px solid #CCC5B8',
    padding: '32px 0',
    cursor: 'pointer',
    transition: 'border-left-color 0.15s, padding-left 0.15s',
  },
  cardCategory: (cat) => ({
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: '3px',
    color: CATEGORY_COLOR[cat] || '#8A8A8A',
    marginBottom: 8,
    fontWeight: 700,
  }),
  cardTitle: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: 'clamp(20px, 3vw, 28px)',
    fontWeight: 700,
    lineHeight: 1.15,
    letterSpacing: '-0.3px',
    marginBottom: 10,
    transition: 'color 0.15s',
  },
  cardMeta: {
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 12,
    color: '#8A8A8A',
    textTransform: 'uppercase',
    letterSpacing: '1.5px',
    fontWeight: 500,
    marginBottom: 10,
  },
  cardExcerpt: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 15,
    lineHeight: 1.7,
    color: '#555555',
    maxWidth: 640,
  },
  articleBack: {
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: '3px',
    color: '#E73B2F',
    cursor: 'pointer',
    border: 'none',
    background: 'transparent',
    padding: '28px 0',
    fontWeight: 700,
    display: 'block',
    textDecoration: 'none',
  },
  articleTitle: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: 'clamp(30px, 5vw, 48px)',
    fontWeight: 700,
    lineHeight: 1.1,
    letterSpacing: '-0.5px',
    color: '#111111',
    marginBottom: 16,
    marginTop: 12,
  },
  articleMeta: {
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 13,
    color: '#8A8A8A',
    textTransform: 'uppercase',
    letterSpacing: '1.5px',
    paddingBottom: 20,
    borderBottom: '2px solid #E73B2F',
    marginBottom: 36,
  },
  cmsBtn: {
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: '2px',
    padding: '11px 22px',
    cursor: 'pointer',
    background: '#E73B2F',
    color: '#FFFFFF',
    border: 'none',
    fontWeight: 700,
  },
  cmsForm: {
    background: '#FFFFFF',
    border: '1px solid #CCC5B8',
    padding: 32,
    marginBottom: 30,
  },
  cmsLabel: {
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: '2px',
    color: '#8A8A8A',
    display: 'block',
    marginBottom: 6,
    marginTop: 20,
  },
  cmsInput: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 14,
    background: '#F5F1E8',
    border: '1px solid #CCC5B8',
    color: '#111111',
    padding: '10px 12px',
    width: '100%',
    boxSizing: 'border-box',
  },
  cmsTextarea: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 15,
    background: '#F5F1E8',
    border: '1px solid #CCC5B8',
    color: '#111111',
    padding: '10px 12px',
    width: '100%',
    minHeight: 200,
    boxSizing: 'border-box',
    lineHeight: 1.7,
    resize: 'vertical',
  },
  cmsSelect: {
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 14,
    background: '#F5F1E8',
    border: '1px solid #CCC5B8',
    color: '#111111',
    padding: '10px 12px',
    width: '100%',
    boxSizing: 'border-box',
  },
  cmsActions: {
    display: 'flex',
    gap: 12,
    marginTop: 24,
  },
  cmsSaveBtn: {
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: '2px',
    padding: '12px 28px',
    cursor: 'pointer',
    background: '#E73B2F',
    color: '#FFFFFF',
    border: 'none',
    fontWeight: 700,
  },
  cmsCancelBtn: {
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: '2px',
    padding: '12px 28px',
    cursor: 'pointer',
    background: 'transparent',
    color: '#8A8A8A',
    border: '1px solid #CCC5B8',
    fontWeight: 500,
  },
  cmsDeleteBtn: {
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: '2px',
    padding: '6px 14px',
    cursor: 'pointer',
    background: 'transparent',
    color: '#E73B2F',
    border: '1px solid #E73B2F',
    fontWeight: 500,
    marginLeft: 'auto',
  },
  neighborhoodPill: {
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: '2px',
    fontWeight: 600,
    padding: '3px 8px',
    border: '1px solid #333',
    background: 'transparent',
    color: '#8A8A8A',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    lineHeight: 1.4,
    display: 'inline-block',
    textDecoration: 'none',
  },
  neighborhoodPillActive: {
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: '2px',
    fontWeight: 600,
    padding: '3px 8px',
    border: '1px solid #F5F1E8',
    background: '#F5F1E8',
    color: '#111111',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    lineHeight: 1.4,
    display: 'inline-block',
    textDecoration: 'none',
  },
  footer: {
    padding: '40px 0',
    textAlign: 'center',
  },
  footerText: {
    fontFamily: "'Archivo Narrow', sans-serif",
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: '3px',
    color: '#8A8A8A',
    lineHeight: 2.2,
  },
}
